# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Ramses Alexander Coraspe Valdez
description: Los repositorios de Ramses Alexander Coraspe Valdez
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://wittline.github.io/"
permalink: :title/
full-url: "https://wittline.github.io/" # the base hostname & protocol for your site

# CSS
sass:
  style: compressed

# Comments - Go to Disqus.com > sign up > get the short-name > insert it here
disqus-shortname: 

# Tracker
analytics:

# Form Settings
#
# Contact form can be enabled by getting an API key from https://getsimpleform.com/
simpleform-token: 

# Redirect users after submitting the form
redirect-to: 

# Site version
version: 0.9

# Post date background - This will change the background of the post date and tag ribbon according to the theme. If set to no default green background will be used. If yes then the theme color scheme is used.

change-date-bg: yes

# Build settings
markdown: kramdown

include: [_pages] # Includes files inside _pages directory [Do not remove this]

author:
  name: Ramses Alexander Coraspe Valdez
  image: w.png # The author image will be shown on the header. Place this image in /images/ folder.
  about: I know you're looking for me a lot on google.
  twitter: ramsescoraspe  # https://twitter.com/ is automatically added
  linkedin: ramsescoraspe # https://www.linkedin.com/in/ is automatically added
  email: contacto@wittline.com # mailto: is automatically added
  
gems: 
  - jekyll-seo-tag
  - jekyll-paginate